- .github/workflows/ci_cd.yml
- pyproject.toml
Closes #47 
This PR updates the CI/CD and pyproject.toml files to reference release versions of packages. Also removes `download-artifact` actions and enables twine upload for releases.
The dependencies are set as follows:
- openapi-common has a `<2.0.0` dependency. i.e. this package will work with any openapi-common that exposes a compatible interface
- bomanalytics-openapi has a `==1.0.0` dependency, i.e. an exact dependency. Multiple versions of this package could depend on bomanalytics-openapi 1.0.0, but if we ever want to bump bomanalytics-openapi, we will be forced to release a new version of grantami-bomanalytics
> Updates to reference released dependencies

- pyproject.toml
This PR closes #127 
Dependabot is erroring because the advertised package Python compatibility is incompatible with pandas. We support 3.7.0 and up, whereas pandas supports 3.7.1 and up. The change here aligns these requirements.
> Bump minimum Python patch version

- .github/dependabot.yml
Skip integration tests when dependabot generates PRs
> CI - Skip integration tests on dependabot PRs

- .github/workflows/ci_cd.yml
Closes #137 
Use the branch name as the filter to determine when to skip integration tests on dependabot automated PRs
> CI - Filter on branch name to skip dependabot integration tests

- .github/workflows/ci_cd.yml
The variable github.ref_name points to the pull request branch, not the source, so the previous change did not skip correctly. This uses the event information to get the source of the PR which does work.
Also simplify the logic around documentation building.
> Fixup workflow trigger and skips

- src/ansys/grantami/bomanalytics/_item_results.py
- src/ansys/grantami/bomanalytics/indicators.py
Closes #147 
This PR fixes the docstring ordering, which was causing warnings with newer versions of numpydoc.
> Fix docstring section ordering

- README.rst
- pyproject.toml
Closes #157 
This PR adds some more context to the documentation link in the README, which ends up on PyPI. It also adds a documentation tag to the pyproject.toml, to ensure the documentation link is added to the sidebar on PyPI.
Closes #125
Also shorten the long line in the quick code section by removing the keyword.
> Fix PyPI Documentation Links

- .github/workflows/server_checks.yml
This PR allows manual execution of integration tests.
This will be useful for dependabot PRs where we want to manually check that integration tests complete successfully, such as for https://github.com/pyansys/grantami-bomanalytics/pull/162
> Allow manual integration tests

- .github/workflows/ci_cd.yml
Closes #156 
Add the `generate_release_flag` argument to the release action. This will automatically summarise contributions to a release on the github releases page.
> [CI]156 - Add generate_release_notes flag to release

- doc/source/conf.py
- examples-dummy/examples/0_Test_module_import.py
- examples-dummy/examples/1_Test_Example/1-1_Test_other_features.py
- examples-dummy/examples/1_Test_Example/index.rst
- examples-dummy/examples/1_Test_Example/supporting-file.txt
- examples-dummy/examples/index.rst
Closes #164 
Creates two example files that test the display-related functionality in the examples. These files go through the same process as the real examples but do not require a live Granta MI instance, so they run much quicker than the real examples.
> Add dummy examples

- src/ansys/grantami/bomanalytics/_connection.py
- src/ansys/grantami/bomanalytics/queries.py
- tests/test_connection.py
Closes #215 
Adds a check as part of the `connect` method to perform a test query. The BoM Analytics service provides the Yaml endpoint which just returns the docs, so the test checks that this query can be performed without raising an exception.
If an exception is raised, then separate error messages are raised depending on whether it's a 404 (service not installed) or something else (probably a 500, check the service layer logs).
> Add client connection check

- .github/workflows/server_checks.yml
Closes #236 
This PR adds the documentation build and packaging steps for the dev portal. Does not currently push those changes to the appropriate branch for publishing, but stores them as a build artefact.
Based on work in https://github.com/pyansys/pyaedt/pull/1747/files
> #236 - Publish Documentation to Dev Portal

- doc/source/conf.py
- poetry.lock
- pyproject.toml
This PR removes the dependency on sphinx_autodoc_typehints. It was only used for removing typehints from signatures in the docs, which is now achieved by sphinx.ext.autodoc
Uses `autodoc_type_aliases` to prevent the fully qualified name of `Yaml` to be output.
> Docs - Remove sphinx_autodoc_typehints dependency

- doc/source/conf.py
- examples/0_Getting_started.py
Move the black `fmt: on` and `fmt: off` flags into separate blocks which are flagged for deletion by the conversion script.
> Separate black flags

- .github/workflows/local_checks.yml
- doc/source/conf.py
- examples/0_Getting_started.py
- examples/1_Impacted_Substances_Queries/1-1_Materials_impacted_substances.py
- examples/1_Impacted_Substances_Queries/1-2_Parts_impacted_substances.py
- examples/2_Compliance_Queries/2-1_Substance_compliance.py
- examples/2_Compliance_Queries/2-2_Material_compliance.py
- examples/2_Compliance_Queries/2-3_Part_compliance.py
- examples/3_Advanced_Topics/3-1_Working_with_XML_BoMs.py
- examples/3_Advanced_Topics/3-2_Dealing_with_external_data_sources.py
- examples/3_Advanced_Topics/3-4_Writing_compliance_results_to_a_dataframe.py
Revert the changes made by #251 to the example Python script formatting. These changes produced very long lines which render with scrollbars in the sphinx theme.
Also required CI changes to avoid build errors.
> Revert black formatting on example scripts

- .github/workflows/dependabot_approve.yml
This PR copies the dependabot-approve workflow from OpenAPI-Common.
Approves PRs by dependabot to reduce need for clicking, must still be reviewed and added the merge queue manually.
> CI - Create dependabot_approve.yml

- .github/workflows/ci_cd.yml
- doc/source/conf.py
- poetry.lock
- pyproject.toml
Modify CI to use doc deployment actions from pyansys/actions v4.
Bump version of sphinx theme to support multi-version
Configures sphinx for multi-version
Currently configured to use cname `bomanalytics.grantami.docs.pyansys.com` which hasn't been requested/verified yet
> Deploy multi version docs to subdomain using pyansys/actions v4

- .github/workflows/ci_cd.yml
- pyproject.toml
- Fix docs url in pyproject
- Fix condition for dev docs deploy
- Fix gh release step: see https://github.com/pyansys/grantami-bomanalytics/releases/tag/untagged-bb564b6493b96d77faba, generated in CI before putting some conditions back
> Fix GitHub release

- .github/workflows/ci_cd.yml
1.1.3 release failed because the upload to pypi is misconfigured after the changes made in #276
> Fix pypi upload wheel path

- .github/workflows/ci_cd.yml
Re-ordered release steps. Action to deploy the docs was deleting the downloaded artifacts, preventing twine from finding them
> Re-order release steps

- doc/source/conf.py
The dev branch of python has renamed the builtin boolean reference, this breaks the docs build. Pin to 3.11 which works fine at present.
> DOC - Update intersphinx mapping to 3.11 not dev

- cicd/connection.py
- cicd/get_cleaned_db_entries.py
- cicd/modify_custom_rs_db.py
- cicd/prepare_rs_db.py
This PR adds a collection of scripts:
1. connection.py provides a serverapi connection client following the docs from serverapi-openapi
2. get_cleaned_db_entries.py collects attribute names and records in a subset from a database, it also performs basic mapping for extra attributes to include and those that have had their names changes
3. prepare_rs_db.py applies these changes, creating a subset and a layout with the appropriate things populated, ready for the database to be cleaned
4. modify_custom_rs_db.py adds extra records for tests and custom table names
These scripts have been tested with the current release and they produce a DB that works with the test suite.
> MAINT - Add scripts to automate backup and restoration of the test database

- cicd/prepare_rs_db.py
Small change to only update records, not create new ones when adding to subsets. This should prevent spurious addition of blank records when cleaning the DB.
> FIX - Update records

- cicd/modify_custom_rs_db.py
- cicd/prepare_rs_db.py
Couple of minor fixes:
1. Fix name of database in modify_custom_rs_db.py - we don't fetch tables after renaming, so we need the old name
2. Only use history GUID to avoid issues with new versions
> CI - Minor script fixes

- cicd/modify_custom_rs_db.py
We need to add the copied record to the default subset to make the test work as intended.
> CI - Add new record to the default subset

- .github/workflows/ci_cd.yml
Latest build failed when trying to deploy development documentation, we should use ansys/actions not pyansys/actions
> CI - Use Ansys repo for dev deployment action

- README.rst
- doc/source/index/quick_code.rst
- examples/0_Getting_started.py
- examples/1_Impacted_Substances_Queries/1-1_Materials_impacted_substances.py
- examples/1_Impacted_Substances_Queries/1-2_Parts_impacted_substances.py
- examples/2_Compliance_Queries/2-1_Substance_compliance.py
- examples/2_Compliance_Queries/2-2_Material_compliance.py
- examples/2_Compliance_Queries/2-3_Part_compliance.py
- examples/3_Advanced_Topics/3-1_Working_with_XML_BoMs.py
- examples/3_Advanced_Topics/3-2_Dealing_with_external_data_sources.py
- examples/3_Advanced_Topics/3-4_Writing_compliance_results_to_a_dataframe.py
- src/ansys/grantami/bomanalytics/_connection.py
- src/ansys/grantami/bomanalytics/_query_results.py
- src/ansys/grantami/bomanalytics/indicators.py
- src/ansys/grantami/bomanalytics/queries.py
- tests/conftest.py
Closes #291 
After the move to use the latest version of the Restricted Substances database for CI, we now see the effects of changing from 'REACH' to 'EU REACH':
https://bomanalytics.grantami.docs.pyansys.com/version/dev/examples/0_Getting_started.html#View-query-results
The REACH legislation 'Short title' was changed from 'REACH - The Candidate List' to 'EU REACH - The Candidate List' to disambiguate from UK REACH, China REACH, Korea REACH, etc. As a result, the examples now return zero results.
This PR replaces 'REACH' with 'EU REACH' everywhere, which should reinstate the results. Check the built docs in the pre-merge checks to confirm.
I have also made a few other miscellaneous documentation changes while I was in the code:
* Fixed a missing space in a connection error string
* …
> #291 Fix EU REACH, and some other miscellaneous documentation improvements

- .github/workflows/local_checks.yml
Warning in the logs about not setting the python version when installing python for the code style checks. This PR uses the `MAIN_PYTHON_VERSION` rather than the non-existent `matrix.python-version`.
> CI - Set Python Version in Code Style Check

- .ipython/profile_default/startup/10-monkeypatch-connection.py
Closes #347 
Use a regular expression to replace the URL in the BomAnalyticsClient repr. Raise a ValueError if no match is found.
> 347 - Use regex to replace server URL

- .github/workflows/ci_cd.yml
- .github/workflows/local_checks.yml
Update the references to two re-usable actions to the `ansys` organization.
I'm not sure why these aren't failing here, but they are causing failures in the private fork. Maybe they are cached in this repo?
> Update action references

- README.rst
- doc/source/getting_started/index.rst
Add instructions for installing this package via the pygranta metapackage.
There isn't as much reuse in this repo as in recordlists, and so the change was required in two places. I have created #389 to see if we can address this in future.
> Add metapackage instructions

- doc/source/api/query_type_differences.rst
- doc/source/conf.py
Update the root url for external links to the product help site.
I've checked all the links with the new root and they all are functioning.
> Docs: update product help links

- .github/labeler.yml
- .github/workflows/label.yml
Add a workflow to automatically label PRs. There will be a follow up PR to use the labels to organize automatically generated release notes.
The configuration is identical to recordlists, which is the default that comes with ansys repo templates.
Labels are applied based on two things:
- location of the modified files
- name of the branch (`maint/*` -> `maintenance`, etc)
> Add labeler workflow

- CHANGELOG.md
- doc/source/api/bom_builder/api.rst
- doc/source/api/bom_builder/index.rst
- doc/source/api/sustainability/index.rst
- src/ansys/grantami/bomanalytics/_bom_helper.py
- src/ansys/grantami/bomanalytics/_connection.py
- src/ansys/grantami/bomanalytics/_item_definitions.py
- src/ansys/grantami/bomanalytics/_item_results.py
- src/ansys/grantami/bomanalytics/_query_results.py
- src/ansys/grantami/bomanalytics/bom_types/_builders.py
- src/ansys/grantami/bomanalytics/indicators.py
- src/ansys/grantami/bomanalytics/queries.py
- src/ansys/grantami/bomanalytics/schemas/__init__.py
Closes #464 
Adds versionadded directives for all additions to the API since the initial release.
General approach was to add them for entire classes if the class is new, or individual properties or attributes if not. Also added to API pages. I didn't add the directive for every BoM type, because we want to keep this somewhat auto-generatable, and adding versionadded directives here wouldn't be possible with that approach.
> Add missing versionadded directives

- cicd/check_server.py
Extend VM timeout - the new VM seems to be much slower at starting up than the previous one, which means CI always fails
> Extend timeout

- doc/changelog.d/513.miscellaneous.md
- doc/source/conf.py
Update openapi-common intersphinx link to accomodate change in object inventory location. (caused by new multiversioned docs)
> Update openapi-common reference link

- version/1.1/api/common.html
- version/1.2/api/common.html
- version/2.0/api/common.html
- version/dev/api/common.html
- version/stable/api/common.html
Closes #516 
Replace `https://openapi.docs.pyansys.com/` with `https://openapi.docs.pyansys.com/version/stable/api`.
I noticed that the link to the general 'API documentation' includes a version number in the `title` attribute, which I believe is what the version happened to be when the documentation was built. I believe this will continue, even referring to the 'stable' version of the intersphinx mapping file, I don't think there's much we can really do about this.
Fairly certain this catches them all.
> Fix cross-references to openapi-common

- .github/workflows/label.yml
- doc/changelog.d/519.changed.md
Closes #515 
Don't run changelog-fragment for dependabot-initiated PRs to avoid dependabot PRs being 'frozen' by someone other than dependabot modifying the branch.
CI on this branch won't be affected, but I'm opening this PR for discussion. @klmcadams I've added you since you've been involved in some of our adventures with the new changelog actions.
> Do not run changelog-fragment for dependabot-initiated PRs

- doc/changelog.d/546.fixed.md
- src/ansys/grantami/bomanalytics/_bom_helper.py
- tests/inputs/__init__.py
- tests/inputs/bom.xml
- tests/test_bom_handler.py
Closes #545 
Standardizes the options used when deserializing a BoM from a file and from a string. Previously, `keep_empty=True` was only specified when reading a BoM from string, which caused a weird asymmetry in some situations.
This PR removes this duplication, and adds some tests that check deserializing and round-tripping a BoM with an empty element works both via a file and via text.
> Empty elements are no longer removed when deserializing a BoM file

- .github/workflows/ci_cd.yml
- doc/changelog.d/549.changed.md
#543 
Modify release CI to use the trusted publisher approach to pushing releases to PyPI
> Use trusted publisher

- .github/workflows/label.yml
- doc/changelog.d/587.changed.md
Ignore pre-commit-ci PRs for changelog fragment creation.
> Don't create changelog fragments for pre-commit updates

- doc/changelog.d/607.documentation.md
- examples/4_Sustainability/supporting-files/bom-2301-assembly.xml
- tests/test_integration_tests.py
Update the hard-coded acceptance test values to align with updated data in the 2025 R1 database.
Also standardize some whitespace and item namings in the test XML BoM.
There is a change to the number of primary processes reported by the BoM Analytics Service, even though the BoM hasn't changed. I believe this is because of the adjusted numbers, and that now this process has just tipped above the threshold to be considered a result in its own right, instead of being lumped in with 'other'.
> Update acceptance tests for 2025 R1 database

- .github/workflows/ci_cd.yml
- doc/changelog.d/617.maintenance.md
Closes #543 
The release action is already using the trusted publisher approach (#549 ), just adding the environment setting.
> Configure environment for trusted publisher release

- README.rst
- doc/changelog.d/620.documentation.md
Add a link to the new page that lists dependencies and their versions for each MI version.
Fix a typo.
> Add link to PyGranta version compatibility documentation

- doc/changelog.d/621.documentation.md
- doc/source/conf.py
- doc/source/getting_started/index.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
https://github.com/ansys/pygranta/issues/109
Adds a link on the `Getting started` page to the list of auth schemes supported by OpenAPI-Common.
> Add link to supported authentication schemes

- .github/workflows/server_checks.yml
- doc/changelog.d/622.maintenance.md
When integration tests failed, the job to check whether there are other active workflow runs was skipped and the VM was always turned off.
Adds a condition on the check_workflow_runs job to always run, unless the whole workflow has been cancelled, in which case the VM shutdown is also skipped.
> Improve VM management in CI

- cicd/get_cleaned_db_entries.py
- cicd/modify_custom_rs_db.py
- cicd/prepare_rs_db.py
- doc/changelog.d/630.documentation.md
- examples/4_Sustainability/supporting-files/bom-2301-assembly.xml
- tests/test_integration_tests.py
Update tests and database preparation scripts for 2025 R1 release.
Test fixes required by changes to data in 2025 R1 database.
> maint: 2025 R1 update

- doc/changelog.d/649.documentation.md
- doc/source/conf.py
Closes #648
Update Ansys doc reference to v251. I have manually checked, and all the docs that use this string work on the internal QA site.
> Update Ansys documentation links to 2025 R1

- doc/changelog.d/654.documentation.md
- doc/source/conf.py
Closes #653 
Use the 2024 R2 documentation site for core software documentation references. Unlike https://github.com/ansys/grantami-recordlists/pull/340 we can't use the public documentation, because the Restricted Substances and Sustainability documentation is only available behind a login.
We have to use the 2024 R2 documentation, because the 2025 R1 documentation will be released after this package.
> Use 2024 R2 Ansys documentation

- README.rst
- doc/changelog.d/656.documentation.md
Update stated Python requirement to 3.10 to 3.13.
I did think about removing this entirely, since we have the badges that give the Python version. The badges are not in the HTML documentation though, so we probably need to keep this line in place,
> Update stated Python requirement

- README.rst
- doc/changelog.d/669.documentation.md
Update the BoM Analytics Services dependency to 2024 R2, which is required because of https://github.com/ansys/grantami-bomanalytics/pull/465.
Also clarify the source of the dependency in the metapackage instructions, as being dependent on BAS, as opposed to Granta MI itself.
This fix should be cherry-picked onto the release/2.2 and release/2.1 branches following merge.
> Fix BoM Analytics Services dependency

- doc/changelog.d/670.fixed.md
- src/ansys/grantami/bomanalytics/_connection.py
Update the advertised minimum BoM Analytics Services version provided in an error message if the services cannot be found.
Also update the error message and constant, to reflect that we are referring to the BAS version, as opposed to the Granta MI version.
This fix should be cherry-picked onto the release/2.2 and release/2.1 branches following merge.
> Update minimum required BoM Analytics Services version

- doc/changelog.d/672.fixed.md
- src/ansys/grantami/bomanalytics/_connection.py
Add missing space to ConnectionError text when BoM Analytics Services is missing.
> Add missing space to ConnectionError text

- doc/changelog.d/702.added.md
- src/ansys/grantami/bomanalytics/_bom_helper.py
- src/ansys/grantami/bomanalytics/bom_types/_bom_reader.py
- tests/inputs/__init__.py
- tests/inputs/bom-with-annotations.xml
- tests/test_bom_handler.py
Add an additional argument to BOM load methods `load_bom_from_file` and `load_bom_from_text` to enforce 'strict' deserialization.
The new argument `allow_unsupported_data` defaults to `True`, which follows the current behavior of allowing data which is compliant with the BoM schema, but is not supported by the classes in the `bom_types` submodule.
This is to allow control when downgrading BoMs as part of the 24/12 work. The downgrading will be implemented as a separate method, and that method will also include this argument. In that case though, the unsupported classes will more likely be caused by more modern BoMs that cannot be fully represented in older versions.
The first in a series of three PRs:
1. This PR
2. https://github.com/ansys/grantami-bomanalytics/pull/703
3. …
> Optionally raise exceptions if a BoM can't be fully deserialized

- cicd/check_server.py
- doc/changelog.d/708.maintenance.md
Closes #705 
Second attempt at making CI more stable, following #706.
This PR replaces the call to BoM Analytics Services with two calls to Server API that depend on the two databases used by this repo. This seemed simpler to write than trying to craft a valid BAS request. I have checked the server while running this script and seen SQL activity, so hopefully this results in improved CI stability.
> Warm up databases

- doc/changelog.d/726.added.md
- doc/source/api/compliance/indicators.rst
- doc/source/conf.py
- poetry.lock
- pyproject.toml
- src/ansys/grantami/bomanalytics/indicators.py
- tests/conftest.py
Use native Sphinx functionality for documenting Enum classes.
This removes the dependency on enum_tools and sphinx-toolbox, and improves the output format of Enums in the documentation.
> Improve documentation of Enum classes

- doc/changelog.d/735.added.md
- tests/test_integration_tests.py
#734 
Add integration tests that validate compliance and impacted substance analysis for 24/12 BoMs.
> Add ImplactedSubstance and Compliance integration tests for 24/12 BoMs

- .github/dependabot.yml
- doc/changelog.d/742.maintenance.md
Azure pypi feeds have an unhelpful extra redirect, we need to add a duplicate entry which has the feed GUID instead of the feed name in order to get dependabot to correctly fetch dependencies.
https://github.com/dependabot/dependabot-core/issues/4780
While we're here let's also add dependency groups as per jobqueue.
> Fix Dependabot Configuration for Private PyPI

- doc/changelog.d/740.dependencies.md
- poetry.lock
Update jinja2 to 3.1.6
Addresses https://github.com/ansys/grantami-bomanalytics/security/dependabot/47
Dependabot isn't working with our password-protected dependencies. @da1910 I know you looked at this here https://github.com/ansys/grantami-jobqueue/blob/main/.github/dependabot.yml, did you get any further with figuring out why it doesn't work?
> Update jinja2 to 3.1.6

- .github/workflows/server_checks.yml
- doc/changelog.d/748.maintenance.md
This change should allow dependabot checks to run fully in parallel:
* If the PR HEAD ref starts with 'dependabot/', then include the ref in the concurrency group, to make the group unique.
* If the PR HEAD ref does not start with 'dependabot/', then don't include the ref (existing behavior).
Dependabot doesn't actually run server checks, but they still need to run through this step so we can ensure they were successfully skipped.
> Allow dependabot server checks to run in parallel

- .github/workflows/ci_cd.yml
- .github/workflows/server_checks.yml
- doc/changelog.d/749.maintenance.md
Move Integration Test check to top-level workflow
This should mean that dependabot checks never run the server_checks job, and as a result never encounter the concurrency issue. Instead, include a no-op step outside of server_checks that either validate the checks completed, or that the job was started by dependabot.
> Move Integration Test check to top-level workflow

- .github/workflows/ci_cd.yml
- doc/changelog.d/772.maintenance.md
Use PyPI-authored publish action, instead of the Ansys-wrapped version.
Copied from https://actions.docs.ansys.com/version/stable/migrations/release-pypi-trusted-publisher.html#release-pypi-trusted-publisher
> Use PyPI-authored publish action

- doc/changelog.d/780.documentation.md
- doc/source/api/bom_builder/index.rst
- doc/source/api/sustainability/index.rst
Closes #777 
Add references to the 24/12 BoM format to the BoM Builder and Sustainability API pages. Also use a `/` in the name, which aligns with our usage elsewhere.
> Add references to 24/12 BoM format in API documentation

- README.rst
- doc/changelog.d/779.documentation.md
Closes #778 
Make sure the supported Granta MI version documentation is clear, and provide additional guidance on identifying compatible versions for older Granta MI reports bundle releases.
The link points to the version table page, which is updated as part of https://github.com/ansys/pygranta/pull/175
> Improve documentation for Granta MI reports bundle version support

- .github/workflows/ci_cd.yml
- .github/workflows/dependabot_approve.yml
- .github/workflows/label.yml
- .github/workflows/server_checks.yml
- doc/changelog.d/785.maintenance.md
Closes #784 
All actions are pinned to the latest available version, except for ansys/actions which are pinned to v9.0.9. See https://github.com/ansys/actions/issues/814 for cause.
> Use git SHA to pin action version

- doc/changelog.d/819.documentation.md
- doc/changelog.d/819.miscellaneous.md
- examples/6_BoMs/6-3_Creating_an_XML_BoM_from_CSV.py
- examples/6_BoMs/index.rst
- examples/supporting-files/glass_door.csv
Close #733 
Add example of processing a CSV file into a BoM.
CSV format matches the output of BoMAnalyzer reports: sequential traversal of the bom, no direct reference to the parent, but a value that represents the level in the BoM.
> Add an example of creating a BoM from a CSV file

- doc/changelog.d/855.miscellaneous.md
- doc/source/api/compliance/bom.rst
- doc/source/api/compliance/indicators.rst
- doc/source/api/impacted_substances/bom.rst
- doc/source/api/sustainability/index.rst
- doc/source/conf.py
Closes #851 
Update the Ansys help links to refer to the 2025 R2 equivalents. The documentation paths have changed in all cases, which required changes to the doc source code as well as the path in conf.py. I also changed the 'Indicators' link to a location which feels more appropriate for the content.
> Refer to the documentation on Ansys Help that relates to the 2025 R2 release

- doc/changelog.d/873.miscellaneous.md
- src/ansys/grantami/bomanalytics/_allowed_types.py
- src/ansys/grantami/bomanalytics/queries.py
- tests/test_allowed_types.py
- tests/test_query_builders/test_bom.py
- tests/test_query_builders/test_materials.py
- tests/test_query_builders/test_parts.py
- tests/test_query_builders/test_specifications.py
- tests/test_query_builders/test_substances.py
This PR re-works the `validate_argument_type` decorator to accept an initial required argument of `argument_name`, which defines which argument will be validated by the decorator instance.
This is required by a separate in-progress PR which will introduce additional arguments to type-checked methods. In these cases, the decorator will be called multiple times for each argument that is to be type checked.
As part of this work, some checks which do not depend on the actual values are now performed when the decorator is initialized. Specifically, checking that unordered collections contain a single item are now done up-front, and raise ValueErrors in these cases.
I did look at using typeguard, but this suffers from the same problem that it did when bomanalytics was first written, in that …
> Re-work allowed_types module to support multiple arguments

- doc/changelog.d/891.miscellaneous.md
- pyproject.toml
- src/ansys/grantami/bomanalytics/_bom_helper.py
Closes #890 
Convert warnings to errors in tests. Fix a deprecation which, as a result of these changes, now fails the tests.
> Convert warnings to errors during tests
