ansys/grantami-bomanalytics

.github/workflows/integration_checks.yml

Use the correct name for the trigger for integration tests

Update workflow trigger

---

pyproject.toml

Update version number for upcoming 1.1 release.

Bump version number to 1.1.0

---

doc/make.bat
doc/source/index.rst
doc/source/index/dependencies.rst
doc/source/index/getting_started.rst
doc/source/latexindex.rst
examples-dummy/examples/index.rst

This PR uses the format of the PyMAPDL Getting Started section to add more important information to the documentation. Covers platform support, python versions, installation instructions and a means to verify the installation.

#212 - Getting Started Section

---

.github/workflows/local_checks.yml
.ipython/profile_default/startup/00-disable-warnings.py
.pre-commit-config.yaml
README.rst
cicd/check_server.py
doc/.vale.ini
doc/source/_static/README.md
doc/source/_templates/autosummary/base.rst
doc/source/_templates/autosummary/class.rst
doc/source/_templates/custom-class-template.rst
doc/source/_templates/custom-module-template.rst
doc/source/api/index.rst
doc/source/conf.py
doc/source/contributing.rst
doc/source/latexindex.rst
doc/styles/.gitignore
doc/styles/Vocab/ANSYS/accept.txt
examples/0_Getting_started.py
examples/1_Impacted_Substances_Queries/1-1_Materials_impacted_substances.py
examples/1_Impacted_Substances_Queries/1-2_Parts_impacted_substances.py
examples/2_Compliance_Queries/2-1_Substance_compliance.py
examples/2_Compliance_Queries/2-2_Material_compliance.py
examples/2_Compliance_Queries/2-3_Part_compliance.py
examples/3_Advanced_Topics/3-1_Working_with_XML_BoMs.py
examples/3_Advanced_Topics/3-2_Dealing_with_external_data_sources.py
examples/3_Advanced_Topics/3-4_Writing_compliance_results_to_a_dataframe.py
src/ansys/grantami/bomanalytics/queries.py

As title says and coming from request on #249 by @PipKat 
I'll leave you the error resolutions! =)

Implementing vale 

---

.github/workflows/server_checks.yml
README.rst
doc/source/_templates/sidebar-nav-bs.html
doc/source/conf.py
doc/source/contributing.rst
poetry.lock
pyproject.toml

- Bump ansys theme version
- Add favicon
- Remove JSON docs build

Docs: bump theme version

---

.github/workflows/ci_cd.yml

Adds trigger for merge queue, should reduce pain when merging dependabot PRs

CI - Add merge queue trigger

---

.github/workflows/ci_cd.yml
.github/workflows/server_checks.yml
pyproject.toml
src/ansys/grantami/bomanalytics/_connection.py
tests/conftest.py
tests/test_integration_tests.py

Closes #277 
I could reproduce the issue following the detailed steps provided. Assessment in the issue is correct, setting the header fixes the issue.
~~I have not added integration tests, as I could not find existing records that would result in the issue, but confirmed fix with a local database.~~
So far decided against making this configurable, since we can't see any use cases for it.
Added an integration test, which required added a new user that would have been able to see the withdrawn record.

Set ActAsReadUser header

---

LICENSE

Closes #287 
Update license date to 2023

MAINT - Update LICENSE

---

examples/0_Getting_started.py
examples/1_Impacted_Substances_Queries/1-1_Materials_impacted_substances.py
src/ansys/grantami/bomanalytics/_connection.py

Closes #259 
Minor text fixes, correct a capitalization, spell material correctly, and a check->checks

DOC - Minor text fixes

---

README.rst
doc/source/api/compliance/indicators.rst
doc/source/api/index.rst
doc/source/conf.py
doc/source/contributing.rst
doc/source/index.rst
doc/source/latexindex.rst
doc/styles/Vocab/ANSYS/accept.txt

Closes #307 
Updates all occurences of `Granta MI BoM Analytics` to `PyGranta BoM Analytics`

Maintenance: Update to PyGranta

---

doc/source/api/query_type_differences.rst

Address vale issues

---

pyproject.toml

Bump version number on main branch

Bump version number (dev)

---

pyproject.toml

Bump version number in advance of 2.0.0 release

Bump version number (2.0 release)

---

pyproject.toml

Fix the package description to include sustainability

Fix package description

---

.pre-commit-config.yaml
README.rst

chore: skip local repos on pre-commit.ci

---

pyproject.toml

Update version number and release classifier for alpha0 release

Prepare for alpha0 release

---

.github/workflows/local_checks.yml
.github/workflows/server_checks.yml
pyproject.toml

It was removed on the private repo for the 2.0 release and was never re-introduced.

Add upload to codecov

---

AUTHORS
CONTRIBUTORS.md

Closes #485 
Adds a contributors and authors file per new style guidance

DOC - Add Contributors and AUTHORS

---

.github/dependabot.yml
.github/labeler.yml
.github/release.yml
.github/workflows/label.yml

Closes #494 
- Fix links in comment added when no labels are found on a PR
- Use GH action
- Add bug fixes to release notes
- Label all dependabot PRs

Update labelling workflow

---

.github/labels.yml
.github/workflows/label.yml
doc/changelog.d/518.changed.md

Closes #514 
* Add labels.yml
* Add label-syncer job to CI
* Configure labeler job to only run on PRs, so CI will still succeed if the labels.yml file is modified

Define labels and add label sync CI

---

pyproject.toml

The classifier was unset when I cherry picked commits from main, reset it to production

MAINT - Update trove classifier

---

.github/workflows/server_checks.yml

Update CI to use release VM on release/2.1 branch.

Use Release VM

---

doc/changelog.d/551.changed.md
pyproject.toml

Update version number on main branch.

Update main branch to 2.2.0dev0

---

README.rst
doc/changelog.d/619.documentation.md

Fix the command and correct the associated statement.

Fix installation example for git dependency

---

AUTHORS
CONTRIBUTORS.md
doc/changelog.d/626.maintenance.md

Closes #624
Closes #625
Update wording and rename AUTHORS
Update wording in CONTRIBUTORS.md

Update CONTRIBUTORS and AUTHORS to new format

---

.github/workflows/server_checks.yml
doc/changelog.d/651.maintenance.md

Use production VM for CI on release branch

Use Production VM for CI on release branch

---

doc/changelog.d/652.maintenance.md
pyproject.toml

Prepare 2.2.0rc0 release

---

doc/changelog.d/668.maintenance.md
pyproject.toml

Prepare for v2.2.0 release
I have previously cherry-picked the following commits onto the release branch:
* 2ff3b63118027bbac2c1185374d3e6188a1dab21
* 1dc64ecc2fb49ca964878e846f34bb7ea5083794
* 827ec11db6694f7f49fbe8995d53c1d86301b335
* df44a7afb5c79ccbd837e0242481ed0b6a3ca745
* d68fb51b48d6983798f1317f2d13051ba7f591f8
* 9a6be68814c71dc3c00f9a262cfb834a55481094 - This one was weird, I think it got merged to the wrong branch. I reverted this commit to main, and cherry-picked it here.

Prepare v2.2.0 release

---

doc/changelog.d/741.dependencies.md
poetry.lock

Update ansys-openapi-common to 2.2.2

Update ansys-openapi-common to 2.2.2

---

.github/workflows/ci_cd.yml
doc/changelog.d/773.maintenance.md

Closes #767 
Add attestation provenance generation to wheelhouse and build jobs.

Generate provenance attestations

---

doc/changelog.d/776.maintenance.md
pyproject.toml

Bump package version to 2.3 to ensure the dev docs are correctly labelled.

Bump version to 2.3

---

.github/workflows/ci_cd.yml
.github/workflows/server_checks.yml
doc/changelog.d/788.dependencies.md
poetry.lock
pyproject.toml

Remove private PyPI references from CI and pyproject.toml

Remove private PyPI references

---

.github/workflows/server_checks.yml
doc/changelog.d/790.maintenance.md

Update test VMs on release branch:
* Remove references to dev machine
* Add references to 2025 R2 release machine

Move release branch to use release VM

---

doc/changelog.d/791.maintenance.md
pyproject.toml

Bump version on main to 2.4.0.dev0

Bump version to 2.4.0.dev0

---

doc/changelog.d/836.miscellaneous.md
poetry.lock

Update all dependencies in lock file

Update lock file

---

SECURITY.md
doc/changelog.d/837.miscellaneous.md

Closes #835 
Add SECURITY.md file

Add SECURITY.md file
